name: Checking Orphaned Debs

on:
  push:
    branches: [ main ]

jobs:
  run-crawler-with-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checking new versions of the debs I am interested in
        run: |
          apt update
          apt install devscripts

          pip install poetry
          poetry install
          # will create or update package_history.pkl in the same dir
          poetry run ./crawler-deb-version.py

